name: Rust

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: update apt
        run: sudo apt update -y
      - name: upgrade
        run: sudo apt upgrade -y
      - name: install dependencies
        run: sudo apt install -y libasound2-dev libgtk-3-dev libatk1.0-dev
      - uses: actions/checkout@v3
      - name: Build
        run: cargo build --verbose
